name: CI Github Test

on:
  # Acione o fluxo de trabalho na solicitação push ou pull,
  # mas apenas para a ramificação principal.
  push:
    branches:
    - master
    - develop
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'
  pull_request:
    branches:
    - master
    tags:        
    - v*

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Teste de instalação do CURL
      run: |
        bash install_dev_script -i curl
        curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx
    - name: Teste de instalação do WGET
      run: |
        bash install_dev_script -i wget
        wget -c https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    - name: Teste de instalação do DBeaver
      run: |
        bash install_dev_script -i dbeaver

